name: Build and Push Docker Images

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest Proton Mail Bridge version
        id: get-version
        run: |
          # Fetch the latest release tag from Proton Mail Bridge GitHub repository
          LATEST_VERSION=$(curl -s https://api.github.com/repos/ProtonMail/proton-bridge/releases/latest | jq -r .tag_name)
          echo "Latest Proton Mail Bridge version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Debian image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ENV_PROTONMAIL_BRIDGE_VERSION=${{ steps.get-version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/proton-mail-bridge:latest
            ghcr.io/${{ github.repository_owner }}/proton-mail-bridge:${{ steps.get-version.outputs.version }}

      - name: Build and push Alpine image
        uses: docker/build-push-action@v5
        with:
          context: ./Alpine
          push: true
          build-args: |
            ENV_PROTONMAIL_BRIDGE_VERSION=${{ steps.get-version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/proton-mail-bridge-alpine:latest
            ghcr.io/${{ github.repository_owner }}/proton-mail-bridge-alpine:${{ steps.get-version.outputs.version }}

      - name: Update README with new version
        run: |
          # Get current date in YYYY/MM/DD format
          CURRENT_DATE=$(date +"%Y/%m/%d")
          
          # Update README.md with new version information
          sed -i "0,/\* [0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}: updated to Proton Mail Bridge v[0-9]\+\.[0-9]\+\.[0-9]\+/s/\* [0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}: updated to Proton Mail Bridge v[0-9]\+\.[0-9]\+\.[0-9]\+/\* $CURRENT_DATE: updated to Proton Mail Bridge ${{ steps.get-version.outputs.version }}/" README.md
          
          # Update Alpine README.md with new version information
          sed -i "0,/\* [0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}: updated to Proton Mail Bridge v[0-9]\+\.[0-9]\+\.[0-9]\+/s/\* [0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}: updated to Proton Mail Bridge v[0-9]\+\.[0-9]\+\.[0-9]\+/\* $CURRENT_DATE: updated to Proton Mail Bridge ${{ steps.get-version.outputs.version }}/" Alpine/README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update to Proton Mail Bridge ${{ steps.get-version.outputs.version }}"
          file_pattern: "README.md Alpine/README.md"